{
  "swagger" : "2.0",
  "info" : {
    "title" : "SWIFTRef API",
    "description" : "SWIFTRef API",
    "version" : "1.0.1-sandbox"
  },
  "schemes" : [ "https" ],
  "paths" : {
    "/ibans/{iban}/validity" : {
      "get" : {
        "tags" : [ "ibans" ],
        "summary" : "Check validity of an IBAN",
        "description" : "You can check whether an IBAN is valid, that is its country code, structure, length, and checksum are valid. It also checks that the bank ID exists and that it is allowed for use in the IBANs. If the bank ID is not allowed, then it is listed in the Exclusion List. This list contains bank IDs that must not be used in IBANs. This validity call allows for very fast, low overhead checking of the validity of an IBAN.",
        "operationId" : "getIbanValidity",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "iban",
          "in" : "path",
          "description" : "IBAN to validate",
          "type" : "string",
          "default" : "BE08363030309814",
          "required" : true
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "The IBAN is valid",
            "schema" : {
              "$ref" : "#/definitions/IbanValidity"
            }
          },
          "400" : {
            "description" : "Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/IbanValidity"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/IbanValidity"
            }
          },
          "404" : {
            "description" : "ISO IBAN country code prefix is not valid or IBAN length is invalid or IBAN checksum is invalid or Bank ID is not known to SWIFT or The bank ID is invalid according to the EXCLUSION LIST or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/IbanValidity"
            }
          }
        }
      }
    },
    "/ibans/{iban}/bic" : {
      "get" : {
        "tags" : [ "ibans" ],
        "summary" : "Get the BIC for an IBAN",
        "description" : "For a given IBAN, you can retrieve the BIC of the institution that services the IBAN. This API is compliant with the requirement for BIC from IBAN derivation defined in the Regulation (EU) No 260/2012.",
        "operationId" : "getBicFromIban",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "iban",
          "in" : "path",
          "description" : "IBAN for which the corresponding BIC is requested",
          "type" : "string",
          "default" : "BE08363030309814",
          "required" : true
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Corresponding BIC found",
            "schema" : {
              "$ref" : "#/definitions/IbanBic"
            }
          },
          "400" : {
            "description" : "Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/IbanBic"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/IbanBic"
            }
          },
          "404" : {
            "description" : "No corresponding BIC found or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/IbanBic"
            }
          }
        }
      }
    },
    "/ibans/{iban}" : {
      "get" : {
        "tags" : [ "ibans" ],
        "summary" : "Get details for an IBAN",
        "description" : "For a given IBAN, you can obtain the components of the IBAN.",
        "operationId" : "getIbanDetails",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "iban",
          "in" : "path",
          "description" : "IBAN for which details are requested",
          "type" : "string",
          "default" : "BE08363030309814",
          "required" : true
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Corresponding IBAN found",
            "schema" : {
              "$ref" : "#/definitions/IbanDetails"
            }
          },
          "400" : {
            "description" : "Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/IbanDetails"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/IbanDetails"
            }
          },
          "404" : {
            "description" : "No corresponding IBAN found or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/IbanDetails"
            }
          }
        }
      }
    },
    "/bbans/{bban}/iban" : {
      "get" : {
        "tags" : [ "bbans" ],
        "summary" : "Get the IBAN from a BBAN",
        "description" : "For a given Basic Bank Account Number (BBAN), you can retrieve the corresponding IBAN; you must also provide a country code",
        "operationId" : "getIbanFromBban",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "bban",
          "in" : "path",
          "description" : "BBAN for which the corresponding IBAN is requested",
          "type" : "string",
          "default" : "539-0075470-34",
          "required" : true
        }, {
          "name" : "country_code",
          "in" : "query",
          "description" : "The 2-character ISO 3166-1 country code of the country that issued the national ID",
          "type" : "string",
          "default" : "BE",
          "required" : true
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Corresponding IBAN found",
            "schema" : {
              "$ref" : "#/definitions/Iban"
            }
          },
          "400" : {
            "description" : "Invalid country code parameter or Invalid parameters or Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/Iban"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/Iban"
            }
          },
          "404" : {
            "description" : "No corresponding IBAN found or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/Iban"
            }
          }
        }
      }
    },
    "/bics/{bic}" : {
      "get" : {
        "tags" : [ "bics" ],
        "summary" : "Get details of a BIC",
        "description" : "For a given BIC, you can retrieve the details of that BIC, that is the bank name or business name, and the address.",
        "operationId" : "getBicDetails",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "bic",
          "in" : "path",
          "description" : "BIC (8-characters or 11-characters) for which details are requested",
          "type" : "string",
          "default" : "",
          "apikey" : "ZGyXZxU6Zmro1YZfJnJyh77IyOkKbb8n",
          "required" : true
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Corresponding BIC found",
            "schema" : {
              "$ref" : "#/definitions/BicDetails"
            }
          },
          "400" : {
            "description" : "Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/BicDetails"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/BicDetails"
            }
          },
          "404" : {
            "description" : "No corresponding BIC found or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/BicDetails"
            }
          }
        }
      }
    },
    "/bics/{bic}/validity" : {
      "get" : {
        "tags" : [ "bics" ],
        "summary" : "Check validity of a BIC",
        "description" : "You can check whether a BIC is correct and valid, that is whether it is published in the BIC Directory; optionally, you can check whether a BIC was valid at a particular date in the past",
        "operationId" : "getBicValidity",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "bic",
          "in" : "path",
          "description" : "BIC (8-characters or 11-characters) to validate",
          "type" : "string",
          "default" : "BANABEBB",
          "required" : true
        }, {
          "name" : "effective_date",
          "in" : "query",
          "description" : "A date in YYYY-MM-DD format",
          "type" : "string",
          "default" : "2018-05-07",
          "required" : false
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Valid BIC",
            "schema" : {
              "$ref" : "#/definitions/BicValidity"
            }
          },
          "400" : {
            "description" : "Invalid BIC format or BIC not supplied or Invalid date parameter or Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/BicValidity"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/BicValidity"
            }
          },
          "404" : {
            "description" : "Invalid BIC or BIC not found or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/BicValidity"
            }
          }
        }
      }
    },
    "/bics/{bic}/lei" : {
      "get" : {
        "tags" : [ "bics" ],
        "summary" : "Get the LEI for a BIC",
        "description" : "For a given BIC, you can retrieve the LEI of that BIC.",
        "operationId" : "getLeiFromBic",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "bic",
          "in" : "path",
          "description" : "BIC (8-characters or 11-characters) for which the corresponding LEI is requested",
          "type" : "string",
          "default" : "BANABEBB",
          "required" : true
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Corresponding LEI found",
            "schema" : {
              "$ref" : "#/definitions/Lei"
            }
          },
          "400" : {
            "description" : "Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/Lei"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/Lei"
            }
          },
          "404" : {
            "description" : "No corresponding LEI found or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/Lei"
            }
          }
        }
      }
    },
    "/leis/{lei}/bic" : {
      "get" : {
        "tags" : [ "leis" ],
        "summary" : "Get the BIC for an LEI",
        "description" : "For a given LEI, you can retrieve the BIC of that LEI.",
        "operationId" : "getBicFromLei",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "lei",
          "in" : "path",
          "description" : "LEI (20-characters) for which the corresponding BIC is requested",
          "type" : "string",
          "default" : "7LTWFZYICNSX8D621K87",
          "required" : true
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Corresponding BIC found",
            "schema" : {
              "$ref" : "#/definitions/Bic"
            }
          },
          "400" : {
            "description" : "Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/Bic"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/Bic"
            }
          },
          "404" : {
            "description" : "No corresponding BIC found or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/Bic"
            }
          }
        }
      }
    },
    "/bics/{bic}/national_ids" : {
      "get" : {
        "tags" : [ "bics" ],
        "summary" : "Get National IDs for a BIC",
        "description" : "For a given BIC, you can retrieve the National IDs of that BIC.",
        "operationId" : "getNationalIdsFromBic",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "bic",
          "in" : "path",
          "description" : "BIC (8-characters or 11-characters) for which the corresponding national IDs are requested",
          "type" : "string",
          "default" : "BANABEBB",
          "required" : true
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Corresponding national ID(s) found",
            "schema" : {
              "$ref" : "#/definitions/NationalIds"
            }
          },
          "400" : {
            "description" : "Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/NationalIds"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/NationalIds"
            }
          },
          "404" : {
            "description" : "No corresponding national ID found or BIC not found or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/NationalIds"
            }
          }
        }
      }
    },
    "/bics/{bic}/reachability" : {
      "get" : {
        "tags" : [ "bics" ],
        "summary" : "Validate SEPA reachability of a BIC",
        "description" : "For a given BIC and SEPA payment scheme, you can validate that it can be reached for SEPA payments and return the SEPA channel CSM (Clearing and Settlement System) through which the bank owning the BIC can be reached; the response also returns the adherence BIC that signed the adherence agreement with the EPC and the intermediary institution's BIC (if applicable and available)",
        "operationId" : "getSepaReachabilityFromBic",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "bic",
          "in" : "path",
          "description" : "BIC (8-characters or 11-characters) for which SEPA reachability is requested",
          "type" : "string",
          "default" : "BANABEBB",
          "required" : true
        }, {
          "name" : "sepa_scheme",
          "in" : "query",
          "description" : "SEPA service code",
          "type" : "string",
          "default" : "SDD",
          "required" : true
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Payment channel(s) found with the supplied BIC and scheme",
            "schema" : {
              "$ref" : "#/definitions/SepaReachability"
            }
          },
          "400" : {
            "description" : "Invalid SEPA scheme parameter or Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/SepaReachability"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/SepaReachability"
            }
          },
          "404" : {
            "description" : "No payment channel found with the supplied BIC and scheme or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/SepaReachability"
            }
          }
        }
      }
    },
    "/bics/{bic}/ssis" : {
      "get" : {
        "tags" : [ "bics" ],
        "summary" : "Get SSIs for a BIC",
        "description" : "For a given BIC, you can retrieve the Standing Settlement Instructions (SSIs) for that BIC, for a given currency, and (optionally) an SSI category (wholesale or retail).",
        "operationId" : "getSsisFromBic",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "bic",
          "in" : "path",
          "description" : "BIC (8-characters or 11-characters) for which the corresponding SSIs are requested",
          "type" : "string",
          "default" : "BANABEBB",
          "required" : true
        }, {
          "name" : "currency_code",
          "in" : "query",
          "description" : "A 3-character currency code for which SSI data needs to be retrieved",
          "type" : "string",
          "default" : "USD",
          "required" : true
        }, {
          "name" : "ssi_category",
          "in" : "query",
          "description" : "Code that indicates the SSI category for which SSI data needs to be retrieved, that is COPA or WHLS",
          "type" : "string",
          "default" : "WHLS",
          "required" : false
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "SSI(s) found with the supplied parameters",
            "schema" : {
              "$ref" : "#/definitions/Ssis"
            }
          },
          "400" : {
            "description" : "Invalid currency parameter or Invalid SSI category parameter or Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/Ssis"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/Ssis"
            }
          },
          "404" : {
            "description" : "No SSI matching the supplied parameters or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/Ssis"
            }
          }
        }
      }
    },
    "/national_ids/{national_id}" : {
      "get" : {
        "tags" : [ "nationalIds" ],
        "summary" : "Get details of a National ID",
        "description" : "For a given National ID, you can retrieve the details of that National ID, that is the bank name or business name, and the address. You must provide either a country code, or an indication to which scheme the National ID belongs.",
        "operationId" : "getNationalIdDetails",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "national_id",
          "in" : "path",
          "description" : "National ID for which details are requested",
          "type" : "string",
          "default" : "999",
          "required" : true
        }, {
          "name" : "country_code",
          "in" : "query",
          "description" : "The 2-character ISO 3166-1 country code of the country that issued the National ID (mandatory, when scheme parameter is not provided)",
          "type" : "string",
          "default" : "BE",
          "required" : false
        }, {
          "name" : "scheme",
          "in" : "query",
          "description" : "The scheme under which the national ID is defined (mandatory, when country_code parameter is not provided)",
          "type" : "string",
          "default" : "ABB-BVB",
          "required" : false
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Corresponding National ID(s) found",
            "schema" : {
              "$ref" : "#/definitions/NationalIdsDetails"
            }
          },
          "400" : {
            "description" : "Invalid scheme parameter or Invalid country code parameter or Invalid parameters or Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/NationalIdsDetails"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/NationalIdsDetails"
            }
          },
          "404" : {
            "description" : "No corresponding National ID found or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/NationalIdsDetails"
            }
          }
        }
      }
    },
    "/national_ids/{national_id}/validity" : {
      "get" : {
        "tags" : [ "nationalIds" ],
        "summary" : "Check the Validity of a National ID",
        "description" : "With this API call, you can check whether a national ID is correct and valid; you need to provide the national ID, and either a country code, or an indication to which scheme this national ID belongs",
        "operationId" : "getNationalIdValidity",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "national_id",
          "in" : "path",
          "description" : "National ID to validate",
          "type" : "string",
          "default" : "999",
          "required" : true
        }, {
          "name" : "country_code",
          "in" : "query",
          "description" : "The 2-character ISO 3166-1 country code of the country that issued the National ID (mandatory, when scheme parameter is not provided)",
          "type" : "string",
          "default" : "BE",
          "required" : false
        }, {
          "name" : "scheme",
          "in" : "query",
          "description" : "The scheme under which the national ID is defined (mandatory, when country_code parameter is not provided)",
          "type" : "string",
          "required" : false
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "The national ID is valid",
            "schema" : {
              "$ref" : "#/definitions/NationalIdValidity"
            }
          },
          "400" : {
            "description" : "Invalid scheme parameter or Invalid country code parameter or Invalid parameters or Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/NationalIdValidity"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/NationalIdValidity"
            }
          },
          "404" : {
            "description" : "The national ID format is valid but it does not exist or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/NationalIdValidity"
            }
          }
        }
      }
    },
    "/national_ids/{national_id}/bics" : {
      "get" : {
        "tags" : [ "nationalIds" ],
        "summary" : "Get BICs of a National ID",
        "description" : "For a given national ID, you can retrieve the BIC or the BICs of that national ID; you need to provide the national ID, and either a country code, or an indication to which scheme this national ID belongs",
        "operationId" : "getBicsFromNationalId",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "national_id",
          "in" : "path",
          "description" : "National ID for which the corresponding BICs are requested",
          "type" : "string",
          "default" : "999",
          "required" : true
        }, {
          "name" : "country_code",
          "in" : "query",
          "description" : "The 2-character ISO 3166-1 country code of the country that issued the National ID (mandatory, when scheme parameter is not provided)",
          "type" : "string",
          "default" : "BE",
          "required" : false
        }, {
          "name" : "scheme",
          "in" : "query",
          "description" : "The scheme under which the national ID is defined (mandatory, when country_code parameter is not provided)",
          "type" : "string",
          "required" : false
        } ],
        "security" : [ {
          "basicAuth" : [ ]
        } ],
        "responses" : {
          "200" : {
            "description" : "Corresponding BIC(s) found",
            "schema" : {
              "$ref" : "#/definitions/Bics"
            }
          },
          "400" : {
            "description" : "Invalid scheme parameter or Invalid country code parameter or Invalid parameters or Wrong URL format or Invalid request",
            "schema" : {
              "$ref" : "#/definitions/Bics"
            }
          },
          "401" : {
            "description" : "You do not have sufficient privileges to execute this service",
            "schema" : {
              "$ref" : "#/definitions/Bics"
            }
          },
          "404" : {
            "description" : "No corresponding BIC found or Wrong URL format",
            "schema" : {
              "$ref" : "#/definitions/Bics"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "IbanValidity" : {
      "type" : "object",
      "properties" : {
        "iban" : {
          "type" : "string",
          "description" : "The IBAN that was validated"
        },
        "validity" : {
          "type" : "string",
          "description" : "The code IVAL if the IBAN is valid"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "status" : {
          "http" : "404",
          "code" : "REDA.API.IIBC",
          "user_message" : "IBAN checksum is invalid",
          "developer_message" : "The IBAN checksum is different from the calculated checksum using the ISO 3166 standard and the MOD97-10 algorithm",
          "more_info" : "ISO 13616, ISO 7064"
        }
      }
    },
    "IbanBic" : {
      "type" : "object",
      "properties" : {
        "bic" : {
          "type" : "string",
          "description" : "The BIC associated with the IBAN"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "bic" : "BANABEBBXXX"
      }
    },
    "IbanDetails" : {
      "type" : "object",
      "properties" : {
        "iban" : {
          "type" : "string",
          "description" : "The IBAN that was validated"
        },
        "country_code" : {
          "type" : "string",
          "description" : "The ISO 3166-1 alpha-2 code of the country of the institution/branch."
        },
        "checksum" : {
          "type" : "string",
          "description" : "The checksum extracted from the IBAN"
        },
        "bank_id" : {
          "type" : "string",
          "description" : "The BANK ID extracted from the IBAN. Its structure (bank ID only or bank ID + branch ID) is as defined by the IBAN BIC LENGTH in the IBANSTRUCTURE file."
        },
        "branch_id" : {
          "type" : "string",
          "description" : "Unique and unambiguous identification of a branch of a financial institution."
        },
        "account_number" : {
          "type" : "string",
          "description" : "The remainder of the IBAN including the account number."
        },
        "length" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The length of the IBAN"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "iban" : "BE08363030309814",
        "country_code" : "BE",
        "checksum" : 8,
        "bank_id" : "363",
        "account_number" : "363030309814",
        "length" : 16
      }
    },
    "Iban" : {
      "type" : "object",
      "properties" : {
        "iban" : {
          "type" : "string",
          "description" : "The corresponding IBAN"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "status" : {
          "http" : "404",
          "code" : "REDA.API.IBNF",
          "user_message" : "No corresponding IBAN found",
          "more_info" : "ISO 13616"
        }
      }
    },
    "Lei" : {
      "type" : "object",
      "properties" : {
        "lei" : {
          "type" : "string",
          "description" : "The corresponding LEI for a given BIC"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "lei" : "7LTWFZYICNSX8D621K87"
      }
    },
    "BicDetails" : {
      "type" : "object",
      "properties" : {
        "bic" : {
          "type" : "string",
          "description" : "The BIC of the institution on which more information is requested"
        },
        "institution_name" : {
          "type" : "string",
          "description" : "Name by which a party is known and which is usually used to identify that party"
        },
        "branch_information" : {
          "type" : "string",
          "description" : "A free text description of the branch as provided by the financial institution to which it belongs; this is currently provided for entries with a BIC when the financial institution concerned wants to provide this extra information"
        },
        "address" : {
          "description" : "Postal address of this institution",
          "$ref" : "#/definitions/Address"
        },
        "contact_details" : {
          "description" : "Information about how the party can be contacted",
          "$ref" : "#/definitions/ContactDetails"
        },
        "office_type" : {
          "type" : "string",
          "description" : "Status of the entity in the office hierarchy"
        },
        "swift_services" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/SwiftService"
          },
          "description" : "A list of 3-character codes and names of SWIFT FIN service codes (also called value added service codes)"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "bic" : "BANABEBBXXX",
        "institution_name" : "BANA BANK IN BELGIUM",
        "branch_information" : "Bana Bank La Hulpe",
        "address" : {
          "address_lines" : [ "Avenue Adèle 1" ],
          "town_name" : "LA HULPE",
          "post_code" : "B-1310",
          "country_name" : "BELGIUM",
          "country_code" : "BE"
        },
        "contact_details" : {
          "phone_number" : "+32 2 655 31 11",
          "fax_number" : "+32 2 655 32 26",
          "email_address" : "bana.bank@swift.com",
          "web_address" : "http://www.swift.com"
        },
        "office_type" : "HO",
        "swift_services" : [ {
          "code" : "TGT",
          "name" : "TARGET2 DIRECT PARTICIPANTS"
        }, {
          "code" : "EBA",
          "name" : "EBA CLEARING - EURO1"
        }, {
          "code" : "ERP",
          "name" : "EBA CLEARING - STEP1"
        }, {
          "code" : "PCH",
          "name" : "SWISS INTERBANK CLEARING (SIC)"
        }, {
          "code" : "SCO",
          "name" : "SCORE FIN"
        }, {
          "code" : "FIN",
          "name" : "Many-to-many FIN payment service"
        } ]
      }
    },
    "BicValidity" : {
      "type" : "object",
      "properties" : {
        "bic" : {
          "type" : "string",
          "description" : "The BIC that was validated"
        },
        "validity" : {
          "type" : "string",
          "description" : "The code VBIC if the BIC is valid"
        },
        "effective_date" : {
          "type" : "string",
          "description" : "A date in YYYY-MM-DD format to indicate explicitly on which date the BIC is confirmed to be valid; the timezone is always UTC, hence the 'Z' suffix will always be present, in compliance with ISO 8601 / RFC 3339"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "bic" : "BANABEBB",
        "validity" : "VBIC",
        "effective_date" : "2018-05-07Z"
      }
    },
    "Address" : {
      "type" : "object",
      "properties" : {
        "address_lines" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          },
          "description" : "An array of maximum 4 lines (strings) expressing the street address of the BIC, e.g. street name, house number, building name and floor, area"
        },
        "post_office_box" : {
          "type" : "string",
          "description" : "Numbered box in a post office, assigned to a person or organisation, where letters are kept until called for"
        },
        "town_name" : {
          "type" : "string",
          "description" : "Name of a built-up area, with defined boundaries, and a local government"
        },
        "country_subdivision" : {
          "type" : "string",
          "description" : "Identifies a subdivision of a country (for example, state, region, county)"
        },
        "post_code" : {
          "type" : "string",
          "description" : "Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail"
        },
        "country_name" : {
          "type" : "string",
          "description" : "The country name in English of the institution/branch as indicated in the ISO 3166 list"
        },
        "country_code" : {
          "type" : "string",
          "description" : "The ISO 3166-1 alpha-2 code of the country of the institution/branch"
        }
      }
    },
    "ContactDetails" : {
      "type" : "object",
      "properties" : {
        "phone_number" : {
          "type" : "string",
          "description" : "Collection of information that identifies a phone number, as defined by telecom services"
        },
        "fax_number" : {
          "type" : "string",
          "description" : "Collection of information that identifies a FAX number, as defined by telecom services"
        },
        "email_address" : {
          "type" : "string",
          "description" : "Address for electronic mail (e-mail)"
        },
        "web_address" : {
          "type" : "string",
          "description" : "Address for the Universal Resource Locator (URL), that is used over the www (HTTP) service"
        }
      }
    },
    "SwiftService" : {
      "type" : "object",
      "properties" : {
        "code" : {
          "type" : "string",
          "description" : "Code given by the service provider (SWIFT) to uniquely identify a service it offers"
        },
        "name" : {
          "type" : "string",
          "description" : "Name given by the service provider (SWIFT) to uniquely identify a service it offers"
        }
      }
    },
    "SepaReachability" : {
      "type" : "object",
      "properties" : {
        "payment_channels" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/SepaPaymentChannel"
          },
          "description" : "SEPA CSM through which the BIC is reachable for the supplied SEPA scheme"
        },
        "adherence_bic" : {
          "type" : "string",
          "description" : "Adherence BIC11 of the reachable BIC"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "payment_channels" : [ {
          "id" : "EBAS",
          "member_type" : "DRCT"
        }, {
          "id" : "DBSC",
          "member_type" : "DRCT"
        } ]
      }
    },
    "SepaPaymentChannel" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "The id of the payment channel (SEPA-compliant CSM)"
        },
        "member_type" : {
          "type" : "string",
          "description" : "A payment channel has a member_type, the member_type has one of the codes DRCT, IDRC or UKWN"
        },
        "direct_participant" : {
          "type" : "string",
          "description" : "The BIC of the direct participant through which the indirectly reachable BIC can be reached; it may only be present if the payment channel's member is an indirect participant"
        }
      }
    },
    "NationalIdsDetails" : {
      "type" : "object",
      "properties" : {
        "national_ids" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/NationalIdDetails"
          }
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "national_ids" : [ {
          "id" : "999",
          "scheme" : "ABB-BVB",
          "institution_name" : "BANA BANK IN BELGIUM, LA HULPE",
          "branch_information" : "(ALL BRANCHES)",
          "address" : {
            "address_lines" : [ "Avenue Adèle 1" ],
            "town_name" : "LA HULPE",
            "post_code" : "1301",
            "country_name" : "BELGIUM",
            "country_code" : "BE"
          },
          "contact_details" : {
            "phone_number" : "+32 2 655 31 11",
            "fax_number" : "+32 2 655 32 26",
            "web_address" : "http://www.swift.com"
          },
          "office_type" : "HO"
        } ]
      }
    },
    "NationalIdDetails" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "National ID for which details were requested"
        },
        "scheme" : {
          "type" : "string",
          "description" : "The scheme under which the national ID is defined"
        },
        "institution_name" : {
          "type" : "string",
          "description" : "Name by which a party is known and which is usually used to identify that party"
        },
        "branch_information" : {
          "type" : "string",
          "description" : "A free text description of the branch as provided by the financial institution to which it belongs; this is currently provided for entries with a BIC when the financial institution concerned wants to provide this extra information"
        },
        "address" : {
          "description" : "Postal address of this institution",
          "$ref" : "#/definitions/Address"
        },
        "contact_details" : {
          "description" : "Information about how the party can be contacted",
          "$ref" : "#/definitions/ContactDetails"
        },
        "office_type" : {
          "type" : "string",
          "description" : "Status of the entity in the office hierarchy"
        }
      }
    },
    "NationalIds" : {
      "type" : "object",
      "properties" : {
        "national_ids" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/NationalId"
          }
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "national_ids" : [ {
          "id" : "999",
          "scheme" : "ABB-BVB"
        } ]
      }
    },
    "NationalId" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string",
          "description" : "The National ID of the institution or branch"
        },
        "type" : {
          "type" : "string",
          "description" : "The type of national ID; if absent, it is the main national ID (MA), otherwise it is Foreign National ID (FN) or Alternative National ID (AN)"
        },
        "scheme" : {
          "type" : "string",
          "description" : "The scheme under which the national ID is defined"
        }
      }
    },
    "Ssis" : {
      "type" : "object",
      "properties" : {
        "ssis" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/Ssi"
          }
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "ssis" : [ {
          "owner_bic" : "BANABEBBXXX",
          "institution_name" : "BANA BANK IN BELGIUM, LA HUKPE",
          "branch_information" : "(ALL BRANCHES)",
          "address" : {
            "address_lines" : [ "Avenue Adèle 1" ],
            "town_name" : "LA HULPE",
            "post_code" : "1301",
            "country_name" : "BELGIUM",
            "country_code" : "BE"
          },
          "currency_code" : "USD",
          "direct" : true,
          "correspondent" : {
            "bic" : "BANABEBB010",
            "preferred" : false
          }
        } ]
      }
    },
    "Ssi" : {
      "type" : "object",
      "properties" : {
        "owner_bic" : {
          "type" : "string",
          "description" : "The owner of the SSI Nostro Account"
        },
        "institution_name" : {
          "type" : "string",
          "description" : "Name by which an institution is known and which is usually used to identify that institution"
        },
        "branch_information" : {
          "type" : "string",
          "description" : "A free text description of the branch as provided by the financial institution to which it belongs; for the time being this will be provided only for entries with a BIC and only when the financial institution concerned wants to provide this extra information; the information is sourced from the BIC Directory"
        },
        "address" : {
          "description" : "Address of the owner of the SSI",
          "$ref" : "#/definitions/Address"
        },
        "currency_code" : {
          "type" : "string",
          "description" : "The ISO 4217 currency code of the requested SSIs"
        },
        "direct" : {
          "type" : "boolean",
          "description" : "Indicates whether there is a direct account relationship between the owner of the SSI and the correspondent; if false, then this means at least the first intermediary must be present"
        },
        "correspondent" : {
          "description" : "The counterparty where the owner BIC is holding the SSI for the specified currency",
          "$ref" : "#/definitions/CorrespondentBic"
        },
        "first_intermediary" : {
          "description" : "Contains the BIC and the Nostro account of the first intermediary with the correspondent; the first intermediary is the owner of the account with the correspondent",
          "$ref" : "#/definitions/IntermediaryBic"
        },
        "second_intermediary" : {
          "description" : "Contains the BIC and the Nostro account of the second intermediary with the first intermediary; the second intermediary is the owner of the account with the first intermediary",
          "$ref" : "#/definitions/IntermediaryBic"
        }
      }
    },
    "CorrespondentBic" : {
      "type" : "object",
      "properties" : {
        "bic" : {
          "type" : "string",
          "description" : "Specifies the BIC"
        },
        "account" : {
          "type" : "string",
          "description" : "The account for a given BIC"
        },
        "preferred" : {
          "type" : "boolean",
          "description" : "Indicates if it is a preferred correspondent, true (yes) or false (no)"
        }
      }
    },
    "IntermediaryBic" : {
      "type" : "object",
      "properties" : {
        "bic" : {
          "type" : "string",
          "description" : "Specifies the BIC"
        },
        "account" : {
          "type" : "string",
          "description" : "The account for a given BIC"
        }
      }
    },
    "NationalIdValidity" : {
      "type" : "object",
      "properties" : {
        "national_id" : {
          "type" : "string",
          "description" : "The national ID that was validated"
        },
        "scheme" : {
          "type" : "string",
          "description" : "The scheme under which the national ID is defined"
        },
        "validity" : {
          "type" : "string",
          "description" : "Contains the code VNID (Valid National ID) if the National ID is valid in the provided scheme or country"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "national_id" : "999",
        "scheme" : "ABB-BVB",
        "validity" : "VNID"
      }
    },
    "Bics" : {
      "type" : "object",
      "properties" : {
        "bics" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          },
          "description" : "An array of the corresponding BICs"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "bics" : [ "BANABEBBXXX" ]
      }
    },
    "Bic" : {
      "type" : "object",
      "properties" : {
        "bic" : {
          "type" : "string",
          "description" : "The corresponding BIC"
        },
        "status" : {
          "$ref" : "#/definitions/Status"
        }
      },
      "example" : {
        "bic" : "BANABEBBXXX"
      }
    },
    "Status" : {
      "type" : "object",
      "required" : [ "http", "code", "user_message" ],
      "properties" : {
        "http" : {
          "type" : "string",
          "description" : "A repeat of the HTTP status code"
        },
        "code" : {
          "type" : "string",
          "description" : "An error code or status code, unique across all SWIFT APIs"
        },
        "user_message" : {
          "type" : "string",
          "description" : "Provided in case your application needs to display a short error message to a human end-user"
        },
        "developer_message" : {
          "type" : "string",
          "description" : "A verbose description for a developer of the possible causes of the error and the possible fixes"
        },
        "more_info" : {
          "type" : "string",
          "description" : "A hyperlink to an explanation of the error for developers, possibly with further pointers to community input"
        }
      }
    }
  },
  "securityDefinitions" : {
    "basicAuth" : {
      "type" : "basic",
      "description" : "HTTP Basic Authentication. Works over `HTTPS`"
    }
  },
  "host" : "swiftapi-test.apigee.net",
  "basePath" : "/swiftref-api"
}
